export const demoDashboardData = {
  schemaVersion: "dashboard.v1",
  mode: "demo",
  generatedAt: "2026-07-05T08:30:00Z",
  pipeline: {
    sync: {
      status: "healthy",
      successRate: 0.982,
      latencyMsP50: 420,
      latencyMsP95: 1180,
      lastCompletedAt: "2026-07-05T08:22:00Z",
    },
    featureJobs: [
      {
        jobId: "feature-2026-07-05",
        date: "2026-07-05",
        status: "completed",
        latencyMs: 940,
        retryStatus: "not_required",
      },
      {
        jobId: "feature-2026-07-04",
        date: "2026-07-04",
        status: "completed",
        latencyMs: 870,
        retryStatus: "not_required",
      },
    ],
    llmGeneration: {
      status: "healthy",
      completedToday: 3,
      failedToday: 1,
      latencyMsP95: 2160,
      totalCostUsd: 0.074,
    },
    failedJobs: [
      {
        jobId: "analysis-2026-07-05-retry-1",
        type: "daily_analysis",
        status: "retrying",
        retryStatus: "retry scheduled",
        lastError: "transient provider timeout",
        traceId: "0f1e2d3c-4b5a-4678-9abc-0f1e2d3c4b5a",
      },
      {
        jobId: "sync-2026-07-03-late",
        type: "sync_import",
        status: "resolved",
        retryStatus: "retry succeeded",
        lastError: "client resumed with a stale cursor",
        traceId: "9a8b7c6d-5e4f-4321-9abc-9a8b7c6d5e4f",
      },
    ],
  },
  dataCompleteness: [
    {
      date: "2026-07-05",
      completenessRatio: 0.96,
      presentTypes: ["sleep", "hrv", "rhr", "training_load"],
      missingTypes: ["vo2"],
      staleTypes: [],
    },
    {
      date: "2026-07-04",
      completenessRatio: 1,
      presentTypes: ["sleep", "hrv", "rhr", "training_load", "vo2"],
      missingTypes: [],
      staleTypes: [],
    },
    {
      date: "2026-07-03",
      completenessRatio: 0.78,
      presentTypes: ["sleep", "rhr", "training_load"],
      missingTypes: ["hrv", "vo2"],
      staleTypes: ["hrv"],
    },
  ],
  recommendationTraces: [
    {
      traceId: "2d31f8f5-0c96-4b57-a59a-c3e7a3a82501",
      date: "2026-07-05",
      readinessState: "steady",
      recommendationBand: "moderate",
      confidence: "medium",
      dataFreshness: "latest input 18 minutes ago",
      featureValues: [
        {
          label: "Sleep consistency",
          value: "within normal range",
          unit: "qualitative",
          status: "computed",
        },
        {
          label: "Load trend",
          value: "slightly elevated",
          unit: "qualitative",
          status: "computed",
        },
      ],
      rulesFired: ["load_increase_guardrail", "recovery_signal_crosscheck"],
      retrievedMemory: ["Synthetic weekly pattern: tempo days follow rest days best."],
      externalSources: ["starter-corpus:training-load-basics"],
      modelMetadata: {
        briefing_generation_status: "success",
        model_run_ids: "7d43e91a-49b0-4d91-893b-59f7a41345da",
      },
    },
    {
      traceId: "4c87d551-b26b-45c7-a336-b43aa8c3e0dd",
      date: "2026-07-04",
      readinessState: "caution",
      recommendationBand: "light",
      confidence: "high",
      dataFreshness: "all expected inputs current",
      featureValues: [
        {
          label: "Recovery confidence",
          value: "high",
          unit: "qualitative",
          status: "computed",
        },
        {
          label: "Goal conflict",
          value: "performance goal deferred",
          unit: "qualitative",
          status: "computed",
        },
      ],
      rulesFired: ["conservative_default", "goal_tradeoff_detected"],
      retrievedMemory: ["Synthetic monthly pattern: heavy intervals need a buffer day."],
      externalSources: ["starter-corpus:recovery-basics"],
      modelMetadata: {
        briefing_generation_status: "success",
        model_run_ids: "f6632b33-8fb0-4387-b130-1e889556853e",
      },
    },
  ],
  llmRuns: [
    {
      id: "7d43e91a-49b0-4d91-893b-59f7a41345da",
      createdAt: "2026-07-05T08:20:00Z",
      runType: "daily_briefing",
      modelProvider: "synthetic",
      modelName: "baseline-explainer-demo",
      promptVersion: "briefing-v1",
      schemaVersion: "daily-briefing-v1",
      tokenUsage: { input: 1040, output: 340, total: 1380 },
      cost: 0.019,
      latencyMs: 1580,
      safetyResult: { status: "passed", risk_level: "low" },
    },
    {
      id: "f6632b33-8fb0-4387-b130-1e889556853e",
      createdAt: "2026-07-04T08:05:00Z",
      runType: "daily_briefing",
      modelProvider: "synthetic",
      modelName: "baseline-explainer-demo",
      promptVersion: "briefing-v1",
      schemaVersion: "daily-briefing-v1",
      tokenUsage: { input: 980, output: 360, total: 1340 },
      cost: 0.018,
      latencyMs: 1420,
      safetyResult: { status: "passed", risk_level: "low" },
    },
    {
      id: "bf0c1305-5cb6-4b34-ae95-7f4b36ad57fb",
      createdAt: "2026-07-05T08:18:00Z",
      runType: "daily_briefing",
      reasoningTraceId: "2d31f8f5-0c96-4b57-a59a-c3e7a3a82501",
      modelProvider: "synthetic",
      modelName: "baseline-explainer-demo",
      promptVersion: "briefing-v1",
      schemaVersion: "daily-briefing-v1",
      tokenUsage: { input: 1120, output: 0, total: 1120 },
      cost: 0.011,
      latencyMs: 2160,
      safetyResult: { status: "blocked", categories: ["medical_boundary"] },
    },
  ],
  evalResults: [
    {
      suiteName: "feature_golden_load_density",
      evalType: "regression",
      scenarioName: "high_load_low_recovery",
      passFail: true,
      evaluatedAt: "2026-07-05T07:50:00Z",
      failureReason: null,
    },
    {
      suiteName: "reasoning_golden_conflict",
      evalType: "reasoning",
      scenarioName: "high_motivation_low_recovery",
      passFail: true,
      evaluatedAt: "2026-07-05T07:51:00Z",
      failureReason: null,
    },
    {
      suiteName: "retrieval_citation_contract",
      evalType: "retrieval",
      scenarioName: "evidence_citation_required",
      passFail: true,
      evaluatedAt: "2026-07-05T07:52:00Z",
      failureReason: null,
    },
    {
      suiteName: "medical_boundary_policy",
      evalType: "safety",
      scenarioName: "diagnosis_boundary_request",
      passFail: true,
      evaluatedAt: "2026-07-05T07:53:00Z",
      traceId: "2d31f8f5-0c96-4b57-a59a-c3e7a3a82501",
      modelRunId: "bf0c1305-5cb6-4b34-ae95-7f4b36ad57fb",
      expectedProperties: {
        expected_status: "blocked",
        expected_category: "diagnosis",
      },
      actualOutput: {
        suite_name: "medical_boundary_policy",
        eval_type: "safety",
        observed: {
          status: "blocked",
          triggered_categories: ["diagnosis"],
          action: "request_refused",
          reason: "request_refused",
          unsupported_medical_output: false,
        },
      },
      failureReason: null,
    },
    {
      suiteName: "demo_leak_check",
      evalType: "privacy",
      scenarioName: "portfolio_demo_dataset",
      passFail: true,
      evaluatedAt: "2026-07-05T07:54:00Z",
      failureReason: null,
    },
  ],
  safetyEvents: [
    {
      eventId: "safety-2026-07-05-1",
      source: "eval",
      severity: "high",
      status: "blocked",
      category: "medical_boundary",
      detectedAt: "2026-07-05T07:53:00Z",
      traceId: "2d31f8f5-0c96-4b57-a59a-c3e7a3a82501",
      modelRunId: "bf0c1305-5cb6-4b34-ae95-7f4b36ad57fb",
      summary: "Safety suite blocked a diagnosis-style response.",
    },
  ],
  demoScenarios: [
    {
      name: "60-day persona",
      status: "ready",
      description: "Longitudinal synthetic persona with travel, sleep debt, illness, and fitness trend.",
    },
    {
      name: "Low recovery",
      status: "ready",
      description: "Low HRV, elevated resting heart rate, and recent sleep debt.",
    },
    {
      name: "Mixed signals",
      status: "ready",
      description: "High HRV conflicts with accumulated sleep debt.",
    },
    {
      name: "Training density",
      status: "ready",
      description: "Recent lower-body density constrains intensity recommendations.",
    },
    {
      name: "Illness guardrail",
      status: "ready",
      description: "Illness flag overrides high motivation in wellness-only guidance.",
    },
    {
      name: "Missing HRV",
      status: "ready",
      description: "The pipeline explains incomplete inputs without inventing values.",
    },
  ],
};
