"""p0_02_core_data_model

Revision ID: d087276a0c2b
Revises:
Create Date: 2026-07-01 18:25:38.862886

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d087276a0c2b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_case",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("scenario_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_fixture", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actual_output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pass_fail", sa.Boolean(), nullable=True),
        sa.Column("failure_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_evaluation_case_evaluated_at", "evaluation_case", ["evaluated_at"], unique=False
    )
    op.create_table(
        "knowledge_source",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_or_org", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "research_paper",
                "book",
                "article",
                "guideline",
                "dataset",
                name="knowledgesourcetype",
            ),
            nullable=False,
        ),
        sa.Column("url_or_identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("license_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "trust_level",
            sa.Enum("peer_reviewed", "authoritative", "curated", "unverified", name="trustlevel"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_knowledge_source_trust_level", "knowledge_source", ["trust_level"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "privacy_mode",
            sa.Enum("local_only", "cloud_assisted", "hybrid", name="privacymode"),
            nullable=False,
        ),
        sa.Column("active_consent_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_created_at", "user", ["created_at"], unique=False)
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "consent_granted",
                "consent_revoked",
                "data_export_requested",
                "data_deleted",
                "sync_completed",
                "recommendation_viewed",
                "feedback_submitted",
                "model_run_logged",
                "safety_flag_triggered",
                name="auditeventtype",
            ),
            nullable=False,
        ),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "redaction_status",
            sa.Enum("redacted", "partial", "none", name="redactionstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_event_user_id_timestamp", "audit_event", ["user_id", "timestamp"], unique=False
    )
    op.create_table(
        "consent_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("consent_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "health_categories_enabled", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("cloud_processing_enabled", sa.Boolean(), nullable=False),
        sa.Column("external_llm_enabled", sa.Boolean(), nullable=False),
        sa.Column("raw_note_processing_enabled", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_consent_record_timestamp", "consent_record", ["timestamp"], unique=False)
    op.create_index("ix_consent_record_user_id", "consent_record", ["user_id"], unique=False)
    op.create_table(
        "daily_check_in",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("energy_score", sa.Integer(), nullable=True),
        sa.Column("mood_score", sa.Integer(), nullable=True),
        sa.Column("soreness_score", sa.Integer(), nullable=True),
        sa.Column("stress_score", sa.Integer(), nullable=True),
        sa.Column("perceived_recovery_score", sa.Integer(), nullable=True),
        sa.Column("food_quality_score", sa.Integer(), nullable=True),
        sa.Column("alcohol_flag", sa.Boolean(), nullable=False),
        sa.Column("caffeine_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("illness_flag", sa.Boolean(), nullable=False),
        sa.Column("injury_flag", sa.Boolean(), nullable=False),
        sa.Column("travel_flag", sa.Boolean(), nullable=False),
        sa.Column(
            "sensitive_note_policy",
            sa.Enum(
                "exclude_from_external_llm",
                "summarize_before_external_llm",
                "allow_external_llm",
                name="sensitivenotepolicy",
            ),
            nullable=False,
        ),
        sa.Column("structured_notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("free_text_note_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_daily_check_in_user_id_date", "daily_check_in", ["user_id", "date"], unique=False
    )
    op.create_table(
        "derived_daily_feature",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("feature_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sleep_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hrv_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rhr_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "training_load_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("recovery_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("goal_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data_quality", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("anomaly_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("source_sample_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_derived_daily_feature_user_id_date",
        "derived_daily_feature",
        ["user_id", "date"],
        unique=False,
    )
    op.create_table(
        "goal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "cognitive_performance",
                "vo2_max",
                "strength",
                "recovery",
                "sleep",
                "long_term_wellness",
                name="goalcategory",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "time_horizon",
            sa.Enum("short_term", "medium_term", "long_term", name="timehorizon"),
            nullable=False,
        ),
        sa.Column("success_metric", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("paused_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_goal_user_id_active", "goal", ["user_id", "active"], unique=False)
    op.create_table(
        "memory_summary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "period_type",
            sa.Enum("daily", "weekly", "monthly", "quarterly", name="periodtype"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("summary_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("observations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hypotheses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "sensitive_fields_excluded", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memory_summary_user_id_period",
        "memory_summary",
        ["user_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_table(
        "model_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "run_type",
            sa.Enum(
                "daily_briefing",
                "explanation",
                "memory_summary",
                "follow_up",
                "safety_check",
                name="runtype",
            ),
            nullable=False,
        ),
        sa.Column("model_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("schema_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("safety_result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_model_run_user_id_created_at", "model_run", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "normalized_health_metric",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "metric_type",
            sa.Enum(
                "heart_rate_variability",
                "resting_heart_rate",
                "steps",
                "active_energy",
                "vo2_max",
                "blood_oxygen",
                "body_temperature",
                "sleep_duration",
                "workout",
                "other",
                name="metrictype",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_sample_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("normalization_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_normalized_health_metric_user_id_start_time",
        "normalized_health_metric",
        ["user_id", "start_time"],
        unique=False,
    )
    op.create_table(
        "raw_health_sample",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_device", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_sample_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "sample_type",
            sa.Enum(
                "heart_rate_variability",
                "resting_heart_rate",
                "steps",
                "active_energy",
                "vo2_max",
                "blood_oxygen",
                "body_temperature",
                "sleep_duration",
                "workout",
                "other",
                name="metrictype",
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("raw_value", sa.Float(), nullable=False),
        sa.Column("raw_unit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_raw_health_sample_user_id_start_time",
        "raw_health_sample",
        ["user_id", "start_time"],
        unique=False,
    )
    op.create_table(
        "readiness_assessment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("assessment_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "readiness_state",
            sa.Enum("high", "moderate", "low", "mixed", "insufficient_data", name="readinessstate"),
            nullable=False,
        ),
        sa.Column(
            "recommendation_band",
            sa.Enum(
                "hard_training_ok",
                "moderate",
                "moderate_or_upper_body",
                "easy",
                "easy_or_recovery",
                "recovery",
                "rest",
                "insufficient_data",
                name="recommendationband",
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence", sa.Enum("low", "medium", "high", name="confidencelevel"), nullable=False
        ),
        sa.Column("uncertainty", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("goal_tradeoffs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasoning_trace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_readiness_assessment_user_id_date",
        "readiness_assessment",
        ["user_id", "date"],
        unique=False,
    )
    op.create_table(
        "sleep_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("sleep_stage_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("interruptions", sa.Integer(), nullable=True),
        sa.Column("quality_proxy", sa.Float(), nullable=True),
        sa.Column("source_sample_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sleep_session_user_id_start_time",
        "sleep_session",
        ["user_id", "start_time"],
        unique=False,
    )
    op.create_table(
        "workout_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column(
            "modality",
            sa.Enum(
                "run",
                "walk",
                "cycle",
                "swim",
                "strength",
                "kettlebell",
                "yoga",
                "mobility",
                "hiit",
                "team_sport",
                "other",
                name="modality",
            ),
            nullable=False,
        ),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("active_energy", sa.Float(), nullable=True),
        sa.Column("average_hr", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Float(), nullable=True),
        sa.Column(
            "intensity_zone_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("perceived_exertion", sa.Integer(), nullable=True),
        sa.Column("muscle_group_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_sample_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workout_session_user_id_start_time",
        "workout_session",
        ["user_id", "start_time"],
        unique=False,
    )
    op.create_table(
        "recommendation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "recommendation_type",
            sa.Enum(
                "training", "recovery", "lifestyle", "follow_up_question", name="recommendationtype"
            ),
            nullable=False,
        ),
        sa.Column("recommendation_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("candidate_options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "safety_status",
            sa.Enum("passed", "blocked", "rewritten", "escalated", name="safetystatus"),
            nullable=False,
        ),
        sa.Column("model_run_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_action", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_recommendation_user_id_date", "recommendation", ["user_id", "date"], unique=False
    )
    op.create_table(
        "normalized_health_metric_source_sample",
        sa.Column("normalized_health_metric_id", sa.Uuid(), nullable=False),
        sa.Column("raw_health_sample_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["normalized_health_metric_id"], ["normalized_health_metric.id"]),
        sa.ForeignKeyConstraint(["raw_health_sample_id"], ["raw_health_sample.id"]),
        sa.PrimaryKeyConstraint("normalized_health_metric_id", "raw_health_sample_id"),
    )
    op.create_table(
        "workout_session_source_sample",
        sa.Column("workout_session_id", sa.Uuid(), nullable=False),
        sa.Column("raw_health_sample_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["workout_session_id"], ["workout_session.id"]),
        sa.ForeignKeyConstraint(["raw_health_sample_id"], ["raw_health_sample.id"]),
        sa.PrimaryKeyConstraint("workout_session_id", "raw_health_sample_id"),
    )
    op.create_table(
        "sleep_session_source_sample",
        sa.Column("sleep_session_id", sa.Uuid(), nullable=False),
        sa.Column("raw_health_sample_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["sleep_session_id"], ["sleep_session.id"]),
        sa.ForeignKeyConstraint(["raw_health_sample_id"], ["raw_health_sample.id"]),
        sa.PrimaryKeyConstraint("sleep_session_id", "raw_health_sample_id"),
    )
    op.create_table(
        "derived_daily_feature_source_sample",
        sa.Column("derived_daily_feature_id", sa.Uuid(), nullable=False),
        sa.Column("raw_health_sample_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["derived_daily_feature_id"], ["derived_daily_feature.id"]),
        sa.ForeignKeyConstraint(["raw_health_sample_id"], ["raw_health_sample.id"]),
        sa.PrimaryKeyConstraint("derived_daily_feature_id", "raw_health_sample_id"),
    )
    op.create_table(
        "derived_daily_feature_source_metric",
        sa.Column("derived_daily_feature_id", sa.Uuid(), nullable=False),
        sa.Column("normalized_health_metric_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["derived_daily_feature_id"], ["derived_daily_feature.id"]),
        sa.ForeignKeyConstraint(["normalized_health_metric_id"], ["normalized_health_metric.id"]),
        sa.PrimaryKeyConstraint("derived_daily_feature_id", "normalized_health_metric_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("derived_daily_feature_source_metric")
    op.drop_table("derived_daily_feature_source_sample")
    op.drop_table("sleep_session_source_sample")
    op.drop_table("workout_session_source_sample")
    op.drop_table("normalized_health_metric_source_sample")
    op.drop_index("ix_recommendation_user_id_date", table_name="recommendation")
    op.drop_table("recommendation")
    op.drop_index("ix_workout_session_user_id_start_time", table_name="workout_session")
    op.drop_table("workout_session")
    op.drop_index("ix_sleep_session_user_id_start_time", table_name="sleep_session")
    op.drop_table("sleep_session")
    op.drop_index("ix_readiness_assessment_user_id_date", table_name="readiness_assessment")
    op.drop_table("readiness_assessment")
    op.drop_index("ix_raw_health_sample_user_id_start_time", table_name="raw_health_sample")
    op.drop_table("raw_health_sample")
    op.drop_index(
        "ix_normalized_health_metric_user_id_start_time", table_name="normalized_health_metric"
    )
    op.drop_table("normalized_health_metric")
    op.drop_index("ix_model_run_user_id_created_at", table_name="model_run")
    op.drop_table("model_run")
    op.drop_index("ix_memory_summary_user_id_period", table_name="memory_summary")
    op.drop_table("memory_summary")
    op.drop_index("ix_goal_user_id_active", table_name="goal")
    op.drop_table("goal")
    op.drop_index("ix_derived_daily_feature_user_id_date", table_name="derived_daily_feature")
    op.drop_table("derived_daily_feature")
    op.drop_index("ix_daily_check_in_user_id_date", table_name="daily_check_in")
    op.drop_table("daily_check_in")
    op.drop_index("ix_consent_record_user_id", table_name="consent_record")
    op.drop_index("ix_consent_record_timestamp", table_name="consent_record")
    op.drop_table("consent_record")
    op.drop_index("ix_audit_event_user_id_timestamp", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index("ix_user_created_at", table_name="user")
    op.drop_table("user")
    op.drop_index("ix_knowledge_source_trust_level", table_name="knowledge_source")
    op.drop_table("knowledge_source")
    op.drop_index("ix_evaluation_case_evaluated_at", table_name="evaluation_case")
    op.drop_table("evaluation_case")

    # Drop native enum types so downgrade returns to a clean base.
    enum_names = [
        "auditeventtype",
        "confidencelevel",
        "goalcategory",
        "knowledgesourcetype",
        "metrictype",
        "modality",
        "periodtype",
        "privacymode",
        "readinessstate",
        "recommendationband",
        "recommendationtype",
        "redactionstatus",
        "runtype",
        "safetystatus",
        "sensitivenotepolicy",
        "timehorizon",
        "trustlevel",
    ]
    for name in enum_names:
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
