"""Add retry_count to DailyAnalysisJob

Revision ID: f11dd261df47
Revises: 5a2d1e4f7b90
Create Date: 2026-07-06 11:26:18.664502

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f11dd261df47"
down_revision: str | None = "5a2d1e4f7b90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_analysis_job",
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("daily_analysis_job", "retry_count", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_analysis_job", "retry_count")
    # ### end Alembic commands ###
